image: electronjs/build:latest
stages:
  - build
before_script:
  - sudo npm install --global yarn

build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/
    - sudo yarn
    - sudo yarn make
    - ls -al
    - ls -al out/
  artifacts:
    expire_in: 1 day
    paths:
      - $CI_PROJECT_DIR/out/make/deb/*.deb
  only:
    - master
