stages:
  - modules
  - build
build:
  image: electronjs/build:latest
  stage: build
  script:
    - nvm
    - node --version
    - npm install --global yarn
    - cd $CI_PROJECT_DIR/src/backend
    - yarn install
    - cd $CI_PROJECT_DIR/
    - yarn install
    - yarn make
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/out/make/deb/x64/*.deb
      - $CI_PROJECT_DIR/out/make/rpm/x64/*.rpm
  only:
    - master
