image: docker:19.03.12
services:
  - docker:19.03.12-dind
stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  image: electronjs/build:latest
  stage: build
  script:
    - cd $CI_PROJECT_DIR/
    - npm i
    - npm run make
  artifacts:
    expire_in: 1 day
    paths:
      - $CI_PROJECT_DIR/make/deb/*.deb
      - $CI_PROJECT_DIR/make/rpm/*.rpm
  only:
    - master
