stages:
  - modules
  - build
variables:
  PORT: 5000
  SECRET: "secret"
  DATABASE: "mongodb://%2Ftmp%2Fbisspropmongodb.sock"
  GIT_SUBMODULE_STRATEGY: normal

make-linux:
  tags:
    - docker
  image: node:latest
  stage: build
  script:
    - node --version
    - apt-get update -y
    - apt-get install -y cmake rpm fakeroot dpkg
    - cd $CI_PROJECT_DIR/src/backend
    - yarn install
    - cd $CI_PROJECT_DIR/
    - yarn install
    - yarn make
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/out/make/deb/x64/*.deb
      - $CI_PROJECT_DIR/out/make/rpm/x64/*.rpm
  only:
    - master
make-win:
  tags:
    - electron
  stage: build
  script:
    - cd $CI_PROJECT_DIR/src/backend
    - yarn install
    - cd $CI_PROJECT_DIR/
    - yarn install
    - yarn make
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/out/make/squirrel.windows/x64/*.exe
      - $CI_PROJECT_DIR/out/make/squirrel.windows/x64/*.nupkg
  only:
    - win
make-mac:
  tags:
    - electron
  stage: build
  script:
    - node --version
    - cd $CI_PROJECT_DIR/src/backend
    - yarn install
    - cd $CI_PROJECT_DIR/
    - yarn install
    - yarn make
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/out/make/*.dmg
  only:
    - master
