image: electronjs/build:latest
stages:
  - build
build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/
    - npm i
    - npm run make
  artifacts:
    expire_in: 1 day
    paths:
      - $CI_PROJECT_DIR/make/deb/*.deb
      - $CI_PROJECT_DIR/make/rpm/*.rpm
  only:
    - master
