image: electronjs/build:latest
stages:
  - build
before_script:
  - sudo npm install --global yarn

build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/
    - sudo yarn
    - sudo yarn make
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/out/make/deb/x64/*.deb
  only:
    - master
